name: bpd_hris
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  auto_size_text: ^3.0.0
  avatar_glow: ^2.0.2
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cherry_toast: ^1.2.1
  flex_color_scheme: ^7.1.1
  fluentui_system_icons: ^1.1.200
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_custom_clippers: ^2.1.0
  flutter_form_builder: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^4.0.0
  flutter_map_location_marker: ^6.0.0
  flutter_svg: ^2.0.5
  form_builder_validators: ^9.0.0
  freezed_annotation: ^2.2.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  go_router: ^7.0.1
  google_fonts: ^4.0.4
  intl: ^0.18.0
  introduction_screen: ^3.1.8
  latlong2: ^0.8.1
  lottie: ^2.3.2
  modal_bottom_sheet: ^3.0.0-pre
  responsive_framework: ^1.0.0
  simple_gradient_text: ^1.2.4
  slide_action: ^0.0.2
  webview_flutter: ^4.2.0

dependency_overrides:
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
